// Code generated by "stringer -type=VideoSource"; DO NOT EDIT.

package atem

import "fmt"

const _VideoSource_name = "Input_1Input_2Input_3Input_4Input_5Input_6Input_7Input_8Input_9Input_10Input_11Input_12Input_13Input_14Input_15Input_16Input_17Input_18Input_19Input_20"

var _VideoSource_index = [...]uint8{0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 71, 79, 87, 95, 103, 111, 119, 127, 135, 143, 151}

func (i VideoSource) String() string {
	if i >= VideoSource(len(_VideoSource_index)-1) {
		return fmt.Sprintf("VideoSource(%d)", i)
	}
	return _VideoSource_name[_VideoSource_index[i]:_VideoSource_index[i+1]]
}
